# Generated by Django 6.0.1 on 2026-02-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='selling_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
