# Generated by Django 6.0.1 on 2026-01-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sales_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('PCS', 'PCS'), ('LTR', 'LTR'), ('MTR', 'MTR')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
