# Generated by Django 6.0.1 on 2026-02-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_mrp_alter_product_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
