# Generated by Django 6.0.1 on 2026-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='daily_salary',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
    ]
