# Generated by Django 6.0.1 on 2026-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staff_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='daily_salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
