# Generated by Django 6.0.1 on 2026-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_daily_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='daily_salary',
        ),
        migrations.AddField(
            model_name='staff',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
