# Generated by Django 6.0.1 on 2026-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staff_daily_salary_staff_monthly_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='monthly_salary',
        ),
        migrations.AddField(
            model_name='staff',
            name='daily_salary',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
