# Generated by Django 6.0.1 on 2026-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_monthly_salary_staff_daily_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='daily_salary',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
