# Generated by Django 6.0.1 on 2026-04-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
