# Generated by Django 6.0.1 on 2026-01-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_purchaseitem_quantity_purchaseitem_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('CREDIT', 'Credit Purchase'), ('CASH', 'Cash Purchase'), ('UPI', 'UPI Purchase'), ('BANK', 'Bank Transfer')], default='CREDIT', max_length=20),
        ),
    ]
