# Generated by Django 6.0.1 on 2026-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchase_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_type',
            field=models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('INCLUSIVE', 'Inclusive')], default='EXCLUSIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('CREDIT', 'Credit Purchase'), ('CASH', 'Cash Purchase'), ('UPI', 'UPI Purchase'), ('BANK', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
