# Generated by Django 6.0.1 on 2026-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_invoicesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='selling_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price for this batch (used in sales)', max_digits=10, null=True),
        ),
    ]
