# Generated by Django 6.0.1 on 2026-02-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchaseitem_selling_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_at_hand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining quantity in this batch', max_digits=10),
        ),
    ]
