# Generated by Django 6.0.1 on 2026-03-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particular', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(choices=[('OPENING', 'Opening Balance'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('MANUAL', 'Manual Entry')], max_length=20)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='supplier_master.supplier')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
