# Generated by Django 6.0.1 on 2026-03-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('work_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.customerwork')),
            ],
        ),
    ]
