# Generated by Django 6.0.1 on 2026-02-07 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_address_customer_created_at_and_more'),
        ('income', '0002_remove_customer_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwork',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
