# Generated by Django 6.0.1 on 2026-02-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_customerledger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLedger',
        ),
    ]
