# Generated by Django 6.0.1 on 2026-03-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='suppliers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
