# Generated by Django 6.0.1 on 2026-01-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_master', '0002_purchase_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
