# Generated by Django 6.0.1 on 2026-02-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_master', '0003_remove_purchaseitem_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
