# Generated by Django 6.0.1 on 2026-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('MAINTENANCE', 'Maintenance'), ('SERVICE', 'Service')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=150)),
                ('care_of', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('maintenance_details', models.TextField(blank=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Finished')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reminder_type', models.CharField(choices=[('CALL', 'Call'), ('PAYMENT', 'Payment'), ('VISIT', 'Visit'), ('OTHER', 'Other')], max_length=20)),
                ('reminder_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
