# Generated by Django 6.0.1 on 2026-04-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Half Day'), ('L', 'Paid Leave')], max_length=1),
        ),
    ]
