# Generated by Django 6.0.1 on 2026-01-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('staff', '0002_remove_staff_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('present', models.IntegerField(default=0)),
                ('half_day', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('daily_salary', models.PositiveIntegerField(default=500)),
                ('advance_amount', models.PositiveIntegerField(default=0)),
                ('total_salary', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
