# Generated by Django 6.0.1 on 2026-02-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchaseitem_selling_rate'),
        ('sales', '0003_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseitem')),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='sales.salesitem')),
            ],
        ),
    ]
