# Generated by Django 6.0.1 on 2026-02-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesitembatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmaster',
            name='sale_type',
            field=models.CharField(choices=[('B2B', 'B2B (Business)'), ('B2C', 'B2C (Consumer)')], default='B2C', max_length=5),
        ),
    ]
